services:
  - type: web
    name: ency
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir moon app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: moon 