services:
  - type: web
    name: ency
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd moon && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production 